### ISSUE TITLE
<repo moved>

### ISSUE THREAD

**Issue by njsmith** [njsmith/urllib3#1]
You probably got here by following a link, huh?

You're looking for: https://github.com/python-trio/urllib3/issues/1

**Comment by nchammas** [comment]
> You probably got here by following a link, huh?

Yep. The link I followed is [here](https://vorpus.org/blog/timeouts-and-cancellation-for-humans/):

> Returning to our initial example: I've been doing some initial work on porting requests to run on Trio (you can help!),

**Comment by njsmith** [comment]
Whoops, thanks! I fixed that link.
