### ISSUE TITLE
Initial runtests.py run fails on macOS - ModuleNotFoundError: No module named 'h11'

### ISSUE THREAD

**Issue by pquentin** [njsmith/urllib3#17]
On macOS (10.13), running `runtests.py` fails because h11 is not installed correctly. This has been true since the beginning of runtests.py, even though I'm only reporting it now.

When installing the dev requirements, I expect "Successfully installed h11-0.7.0+dev" but I see "Successfully installed h11". Even though pip reports success, `h11` and `h11-0.7.0+dev-py3.6.egg-info` are not in `test-venv-cp36m-macosx_10_13_x86_64/lib/python3.6/site-packages`.

Workarounds:

 * Using `venv` instead of `virtualenv`, but we want to support Python 2 eventually so that's not useful
 * Install h11 manually in the newly created venv
 * Activate the newly created venv, install an updated wheel, then run `runtests.py`

I tried to use activate_this.py without much success. I've wasted a lot of time with this issue, so I'm not planning to investigate further, but I thought I would report what I've tried.

**Comment by njsmith** [comment]
Do we actually need h11 from git? Can we just switch to installing it from
pypi like everything else?

**Comment by pquentin** [comment]
The tests do work with h11 0.7.0, yes, even if it's quite old. I'll try to
prepare a pull request to this effect.

Le lun. 19 mars 2018 20:18, Nathaniel J. Smith <notifications@github.com> a
écrit :

**Comment by pquentin** [comment]
Actually https://github.com/njsmith/h11/commit/75e271cab4a5797b1ade0e232693bec12c95ea9d is needed, which was added for the urllib3 tests and is the reason why we're installing from git in the first place. Maybe consider releasing a new h11 version?

**Comment by njsmith** [comment]
Ah hah, thanks for tracking that down. And yeah, I'll release a new version.
